language: node_js
node_js:
  - node
  - 12
  - 8
  - 6
script:
  - export NODE_ENV=test
  - npm run build
  - npm run test
after_success:
  - export NODE_ENV=production
  - npm run build
notifications:
  email: false
sudo: false
